In [1]:
import pandas as pd
import seaborn as sns

In [10]:
df = pd.read_csv('c.csv')

In [3]:
df.isnull().any()
missing_values = ['NONE', 'None', 'none', 'NAN', 'Nan', 'nan', 'NA', 'Na', 'na', 'NaN']
df = pd.read_csv('c.csv', na_values = missing_values)
df.isnull().sum()

s6.new.rev.p2.m2              0
s1.new.rev.m1                 0
s3.og.rev.4db.p5              0
s3.new.rev.4db.p5             0
s4.usg.ins.p2                 0
                             ..
s3.og.rev.all.m2              0
s3.new.rev.m2                 0
prop.og.mou.any.p6            0
prop.loc.i2i.mou.og.mou.p3    0
s3.rev.p1                     0
Length: 111, dtype: int64

In [6]:
df.dropna(inplace=True)

In [13]:
df.describe()

,s6.new.rev.p2.m2,s1.new.rev.m1,s3.og.rev.4db.p5,s3.new.rev.4db.p5,s4.usg.ins.p2,s4.og.unq.any.p2,s2.rch.val.p6,s1.og.rev.all.m1,s8.new.rev.p6,s4.loc.ic.ins.p1,...,prop.og.mou.tot.mou.all.p6,prop.i2i.og.mou.p6,s4.loc.ic.ins.p2,s4.std.ic.ins.l14,s4.low.blnc.ins.p4,s3.og.rev.all.m2,s3.new.rev.m2,prop.og.mou.any.p6,prop.loc.i2i.mou.og.mou.p3,s3.rev.p1
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,...,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,-0.003730,281.073083,4.890003,7.070194,5.460080,28.532520,72.208906,218.517937,-0.028327,3.254720,...,0.538407,0.485523,5.731280,1.797320,8.382160,8.008660,12.540182,53.594165,0.483975,9.951366
std,2.727916,276.075983,4.212452,6.318992,2.184444,28.061435,67.921490,231.321064,0.354573,1.193271,...,0.209203,0.271146,1.936848,3.048943,8.961016,6.152429,11.540611,21.408486,0.292349,17.648128
min,-1.000000,0.000000,0.000000,0.000833,0.000000,0.000000,0.000000,0.000000,-5.090000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-0.580000,101.563800,2.367288,3.318825,5.000000,9.000000,33.000000,74.420000,-0.160000,3.000000,...,0.394227,0.274034,5.000000,0.000000,1.000000,4.207500,6.167500,39.378142,0.251304,1.970000
50%,-0.170000,204.859600,3.729944,5.231268,7.000000,21.000000,52.260000,151.168500,-0.020000,4.000000,...,0.539354,0.476759,7.000000,0.000000,5.000000,6.345000,9.350000,53.976203,0.477621,5.380000
75%,0.280000,370.711650,5.993342,8.395736,7.000000,39.000000,89.852500,284.265000,0.110000,4.000000,...,0.682695,0.694104,7.000000,2.000000,14.000000,9.830000,14.620000,68.312416,0.716538,11.400000
max,316.860000,5702.924300,153.221695,170.200441,7.000000,622.000000,2249.000000,3767.565000,5.000000,4.000000,...,1.000000,1.000000,7.000000,14.000000,30.000000,171.780000,386.480000,100.000000,1.000000,585.500000

In [5]:
# Define the threshold (80% in this case)
threshold = 0.70

# Calculate the number of rows in the DataFrame
total_rows = len(df)

# Iterate over each column
for column in df.columns:
    # Calculate the ratio of unique values to the total number of rows
    unique_ratio = df[column].nunique() / total_rows
    # Check if the ratio exceeds the threshold
    if unique_ratio > threshold:
        # Drop the column
        df.drop(column, axis=1, inplace=True)

# Write the modified DataFrame back to a CSV file
df.to_csv('unique.csv', index=False)

In [6]:
df

,s6.new.rev.p2.m2,s4.usg.ins.p2,s4.og.unq.any.p2,s2.rch.val.p6,s8.new.rev.p6,s4.loc.ic.ins.p1,s8.mbl.p2,s2.rch.val.l67,s7.s4.day.no.mou.p2.p4,s3.new.rev.p3,...,s4.loc.ins.l14,s4.low.blnc.ins.m2,s4.data.ins.l14,s4.dec.ins.p2,s4.loc.ic.ins.p2,s4.std.ic.ins.l14,s4.low.blnc.ins.p4,s3.og.rev.all.m2,s3.new.rev.m2,s3.rev.p1
0,-0.76,4,14,39.29,-0.17,1,-0.72,39.44,1.000000,7.16,...,12,3,0,4,4,0,9,6.02,8.20,0.22
1,-0.98,1,2,21.67,-0.32,3,-0.08,18.89,0.500000,1.10,...,13,16,0,1,6,0,20,3.66,8.10,0.38
2,-0.98,2,3,30.00,-0.05,3,-0.09,29.50,0.384615,4.19,...,14,12,0,2,6,1,19,4.33,4.36,0.11
3,-0.92,2,3,50.00,-0.18,4,1.83,46.67,0.416667,0.40,...,14,8,0,2,7,2,11,3.40,3.53,5.18
4,-0.97,3,2,22.50,0.01,4,-0.04,37.20,0.222222,5.12,...,14,20,2,3,6,1,14,3.85,3.87,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0.21,5,8,26.67,-0.16,4,0.76,39.17,0.250000,3.91,...,12,19,0,5,7,0,18,3.57,3.83,0.76
24996,0.80,2,8,27.88,0.19,4,0.37,25.21,0.454545,8.77,...,13,18,0,2,7,0,18,6.89,7.70,12.74
24997,0.01,6,10,10.00,-0.03,2,-0.79,11.30,0.083333,4.48,...,9,15,1,5,3,0,12,6.63,7.48,8.07
24998,0.17,7,67,42.92,0.70,4,-1.09,40.02,99.000000,24.49,...,14,1,3,4,7,1,1,19.36,22.26,21.21
24999,-1.00,1,1,53.50,-0.48,4,0.00,52.50,0.400000,0.01,...,14,11,0,1,7,0,18,5.42,8.02,0.00

In [7]:
# Read the CSV file into a DataFrame
df = pd.read_csv('unique.csv')

# Define the threshold (0 % in this case)
threshold = 0.0

# Calculate the total number of rows in the DataFrame
total_rows = len(df)

# Iterate over each column
for column in df.columns:
    # Calculate the variance of the column
    column_variance = df[column].var()
    # Calculate the ratio of non-zero variance values to the total number of rows
    variance_ratio = column_variance / total_rows
    # Check if the ratio is below the threshold
    if variance_ratio < threshold:
        # Drop the column
        df.drop(column, axis=1, inplace=True)

# Write the modified DataFrame back to a CSV file
df.to_csv('variance.csv', index=False)

In [8]:
df

,s6.new.rev.p2.m2,s4.usg.ins.p2,s4.og.unq.any.p2,s2.rch.val.p6,s8.new.rev.p6,s4.loc.ic.ins.p1,s8.mbl.p2,s2.rch.val.l67,s7.s4.day.no.mou.p2.p4,s3.new.rev.p3,...,s4.loc.ins.l14,s4.low.blnc.ins.m2,s4.data.ins.l14,s4.dec.ins.p2,s4.loc.ic.ins.p2,s4.std.ic.ins.l14,s4.low.blnc.ins.p4,s3.og.rev.all.m2,s3.new.rev.m2,s3.rev.p1
0,-0.76,4,14,39.29,-0.17,1,-0.72,39.44,1.000000,7.16,...,12,3,0,4,4,0,9,6.02,8.20,0.22
1,-0.98,1,2,21.67,-0.32,3,-0.08,18.89,0.500000,1.10,...,13,16,0,1,6,0,20,3.66,8.10,0.38
2,-0.98,2,3,30.00,-0.05,3,-0.09,29.50,0.384615,4.19,...,14,12,0,2,6,1,19,4.33,4.36,0.11
3,-0.92,2,3,50.00,-0.18,4,1.83,46.67,0.416667,0.40,...,14,8,0,2,7,2,11,3.40,3.53,5.18
4,-0.97,3,2,22.50,0.01,4,-0.04,37.20,0.222222,5.12,...,14,20,2,3,6,1,14,3.85,3.87,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0.21,5,8,26.67,-0.16,4,0.76,39.17,0.250000,3.91,...,12,19,0,5,7,0,18,3.57,3.83,0.76
24996,0.80,2,8,27.88,0.19,4,0.37,25.21,0.454545,8.77,...,13,18,0,2,7,0,18,6.89,7.70,12.74
24997,0.01,6,10,10.00,-0.03,2,-0.79,11.30,0.083333,4.48,...,9,15,1,5,3,0,12,6.63,7.48,8.07
24998,0.17,7,67,42.92,0.70,4,-1.09,40.02,99.000000,24.49,...,14,1,3,4,7,1,1,19.36,22.26,21.21
24999,-1.00,1,1,53.50,-0.48,4,0.00,52.50,0.400000,0.01,...,14,11,0,1,7,0,18,5.42,8.02,0.00

In [4]:
import pandas as pd
import numpy as np

# Read the CSV file into a DataFrame
df = pd.read_csv('variance.csv')

# Define the threshold for outlier detection (e.g., +/-3 sigma)
threshold = 3

# Define a function for outlier treatment using standardization
def treat_outliers(df):
    # Calculate the mean and standard deviation for each column
    mean = df.mean()
    std_dev = df.std()
    
    # Detect outliers using the +/-3 sigma approach
    lower_bound = mean - threshold * std_dev
    upper_bound = mean + threshold * std_dev
    
    # Replace outliers with the nearest bound
    df_clipped = df.clip(lower=lower_bound, upper=upper_bound, axis=1)
    
    return df_clipped

# Apply outlier treatment to each column
df_treated = treat_outliers(df)

# Write the treated DataFrame back to a CSV file
df_treated.to_csv('standardization.csv', index=False)

In [5]:
df_treated

,s6.new.rev.p2.m2,s4.usg.ins.p2,s4.og.unq.any.p2,s2.rch.val.p6,s8.new.rev.p6,s4.loc.ic.ins.p1,s8.mbl.p2,s2.rch.val.l67,s7.s4.day.no.mou.p2.p4,s3.new.rev.p3,...,s4.loc.ins.l14,s4.low.blnc.ins.m2,s4.data.ins.l14,s4.dec.ins.p2,s4.loc.ic.ins.p2,s4.std.ic.ins.l14,s4.low.blnc.ins.p4,s3.og.rev.all.m2,s3.new.rev.m2,s3.rev.p1
0,-0.76,4,14.0,39.29,-0.17,1,-0.72,39.44,1.000000,7.16,...,12.0,3,0,4,4,0.0,9,6.02,8.20,0.22
1,-0.98,1,2.0,21.67,-0.32,3,-0.08,18.89,0.500000,1.10,...,13.0,16,0,1,6,0.0,20,3.66,8.10,0.38
2,-0.98,2,3.0,30.00,-0.05,3,-0.09,29.50,0.384615,4.19,...,14.0,12,0,2,6,1.0,19,4.33,4.36,0.11
3,-0.92,2,3.0,50.00,-0.18,4,1.83,46.67,0.416667,0.40,...,14.0,8,0,2,7,2.0,11,3.40,3.53,5.18
4,-0.97,3,2.0,22.50,0.01,4,-0.04,37.20,0.222222,5.12,...,14.0,20,2,3,6,1.0,14,3.85,3.87,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0.21,5,8.0,26.67,-0.16,4,0.76,39.17,0.250000,3.91,...,12.0,19,0,5,7,0.0,18,3.57,3.83,0.76
24996,0.80,2,8.0,27.88,0.19,4,0.37,25.21,0.454545,8.77,...,13.0,18,0,2,7,0.0,18,6.89,7.70,12.74
24997,0.01,6,10.0,10.00,-0.03,2,-0.79,11.30,0.083333,4.48,...,9.0,15,1,5,3,0.0,12,6.63,7.48,8.07
24998,0.17,7,67.0,42.92,0.70,4,-1.09,40.02,99.000000,24.49,...,14.0,1,3,4,7,1.0,1,19.36,22.26,21.21
24999,-1.00,1,1.0,53.50,-0.48,4,0.00,52.50,0.400000,0.01,...,14.0,11,0,1,7,0.0,18,5.42,8.02,0.00

In [9]:
# Read the CSV file into a DataFrame
df = pd.read_csv('variance.csv')

# Define the threshold for outlier detection (e.g., 1.5 times the IQR)
threshold = 1.5

# Iterate over each numerical column
for column in df.select_dtypes(include=['number']).columns:
    # Calculate the quartiles
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    
    # Calculate the Interquartile Range (IQR)
    IQR = Q3 - Q1
    
    # Define the lower and upper bounds
    lower_bound = Q1 - threshold * IQR
    upper_bound = Q3 + threshold * IQR
    
    # Identify outliers
    outliers = (df[column] < lower_bound) | (df[column] > upper_bound)
    
    # Replace outliers with NaN or the nearest bound
    #df[column] = df[column].mask(outliers, None)  # Replace with NaN
    # Alternatively, you can replace outliers with the nearest bound:
    df[column] = df[column].clip(lower=lower_bound, upper=upper_bound)
    
# Write the modified DataFrame back to a CSV file
df.to_csv('boxplot.csv', index=False)

In [10]:
df

,s6.new.rev.p2.m2,s4.usg.ins.p2,s4.og.unq.any.p2,s2.rch.val.p6,s8.new.rev.p6,s4.loc.ic.ins.p1,s8.mbl.p2,s2.rch.val.l67,s7.s4.day.no.mou.p2.p4,s3.new.rev.p3,...,s4.loc.ins.l14,s4.low.blnc.ins.m2,s4.data.ins.l14,s4.dec.ins.p2,s4.loc.ic.ins.p2,s4.std.ic.ins.l14,s4.low.blnc.ins.p4,s3.og.rev.all.m2,s3.new.rev.m2,s3.rev.p1
0,-0.76,4,14,39.29,-0.170,1.5,-0.72,39.44,1.000000,7.16,...,12.0,3,0,4,4,0,9,6.02000,8.20,0.22
1,-0.98,2,2,21.67,-0.320,3.0,-0.08,18.89,0.500000,1.10,...,13.0,16,0,1,6,0,20,3.66000,8.10,0.38
2,-0.98,2,3,30.00,-0.050,3.0,-0.09,29.50,0.384615,4.19,...,14.0,12,0,2,6,1,19,4.33000,4.36,0.11
3,-0.92,2,3,50.00,-0.180,4.0,1.83,46.67,0.416667,0.40,...,14.0,8,0,2,7,2,11,3.40000,3.53,5.18
4,-0.97,3,2,22.50,0.010,4.0,-0.04,37.20,0.222222,5.12,...,14.0,20,2,3,6,1,14,3.85000,3.87,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0.21,5,8,26.67,-0.160,4.0,0.76,39.17,0.250000,3.91,...,12.0,19,0,5,7,0,18,3.57000,3.83,0.76
24996,0.80,2,8,27.88,0.190,4.0,0.37,25.21,0.454545,8.77,...,13.0,18,0,2,7,0,18,6.89000,7.70,12.74
24997,0.01,6,10,10.00,-0.030,2.0,-0.79,11.30,0.083333,4.48,...,11.5,15,1,5,3,0,12,6.63000,7.48,8.07
24998,0.17,7,67,42.92,0.515,4.0,-1.09,40.02,99.000000,24.49,...,14.0,1,3,4,7,1,1,18.26375,22.26,21.21
24999,-1.00,2,1,53.50,-0.480,4.0,0.00,52.50,0.400000,0.01,...,14.0,11,0,1,7,0,18,5.42000,8.02,0.00

In [11]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('variance.csv')

# Define the threshold for outlier detection (e.g., 1.5 times the IQR)
threshold = 1.5

# Define a function for outlier treatment using capping and flooring
def treat_outliers(column):
    Q1 = column.quantile(0.25)
    Q3 = column.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - threshold * IQR
    upper_bound = Q3 + threshold * IQR
    # Cap and floor outliers
    column = column.clip(lower=lower_bound, upper=upper_bound)
    return column

# Apply outlier treatment to each column
for column in df.columns:
    df[column] = treat_outliers(df[column])

# Write the modified DataFrame back to a CSV file
df.to_csv('cf.csv', index=False)

In [12]:
df

,s6.new.rev.p2.m2,s4.usg.ins.p2,s4.og.unq.any.p2,s2.rch.val.p6,s8.new.rev.p6,s4.loc.ic.ins.p1,s8.mbl.p2,s2.rch.val.l67,s7.s4.day.no.mou.p2.p4,s3.new.rev.p3,...,s4.loc.ins.l14,s4.low.blnc.ins.m2,s4.data.ins.l14,s4.dec.ins.p2,s4.loc.ic.ins.p2,s4.std.ic.ins.l14,s4.low.blnc.ins.p4,s3.og.rev.all.m2,s3.new.rev.m2,s3.rev.p1
0,-0.76,4,14,39.29,-0.170,1.5,-0.72,39.44,1.000000,7.16,...,12.0,3,0,4,4,0,9,6.02000,8.20,0.22
1,-0.98,2,2,21.67,-0.320,3.0,-0.08,18.89,0.500000,1.10,...,13.0,16,0,1,6,0,20,3.66000,8.10,0.38
2,-0.98,2,3,30.00,-0.050,3.0,-0.09,29.50,0.384615,4.19,...,14.0,12,0,2,6,1,19,4.33000,4.36,0.11
3,-0.92,2,3,50.00,-0.180,4.0,1.83,46.67,0.416667,0.40,...,14.0,8,0,2,7,2,11,3.40000,3.53,5.18
4,-0.97,3,2,22.50,0.010,4.0,-0.04,37.20,0.222222,5.12,...,14.0,20,2,3,6,1,14,3.85000,3.87,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0.21,5,8,26.67,-0.160,4.0,0.76,39.17,0.250000,3.91,...,12.0,19,0,5,7,0,18,3.57000,3.83,0.76
24996,0.80,2,8,27.88,0.190,4.0,0.37,25.21,0.454545,8.77,...,13.0,18,0,2,7,0,18,6.89000,7.70,12.74
24997,0.01,6,10,10.00,-0.030,2.0,-0.79,11.30,0.083333,4.48,...,11.5,15,1,5,3,0,12,6.63000,7.48,8.07
24998,0.17,7,67,42.92,0.515,4.0,-1.09,40.02,99.000000,24.49,...,14.0,1,3,4,7,1,1,18.26375,22.26,21.21
24999,-1.00,2,1,53.50,-0.480,4.0,0.00,52.50,0.400000,0.01,...,14.0,11,0,1,7,0,18,5.42000,8.02,0.00

In [13]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('cf.csv')

# Define the threshold for correlation
threshold = 0.90  # You can adjust this threshold based on your requirement

# Calculate the correlation matrix
corr_matrix = df.corr().abs()

# Create a mask to identify highly correlated features
mask = (corr_matrix >= threshold) & (corr_matrix < 1)

# Get the names of highly correlated features
highly_correlated_features = set()
for col in mask.columns:
    correlated_cols = mask.index[mask[col]].tolist()
    if correlated_cols:
        highly_correlated_features.add(col)
        highly_correlated_features.update(correlated_cols)

# Remove highly correlated features from the DataFrame
df_filtered = df.drop(highly_correlated_features, axis=1)

# Write the filtered DataFrame back to a CSV file
df_filtered.to_csv('co.csv', index=False)

In [14]:
df_filtered

,s8.mbl.p2,s7.s4.day.no.mou.p2.p4,s3.new.rev.p3,s7.s5.s4.day.nomou.p4,s8.og.rev.p3,s8.ic.mou.all.p3,target,s7.rev.p2.p6,s7.new.rev.p3.p6,ds.usg.p6,...,s1.loc.og.mou.p1,s7.rtd.mou.l21.p6,s8.rtd.mou.p3,s8.rev.p6,s5.rev.p2,s4.rch.val.gt.30.p2,s4.loc.ins.l14,s4.data.ins.l14,s3.og.rev.all.m2,s3.new.rev.m2
0,-0.72,1.000000,7.16,0.666667,-0.600,-0.73,1,0.030,0.340,0,...,2.383200,0.460,-0.500,-0.120,7.04000,0.0,12.0,0,6.02000,8.20
1,-0.08,0.500000,1.10,0.583333,-0.140,0.00,1,0.010,0.050,0,...,0.650000,0.240,-0.110,-0.220,0.76000,0.0,13.0,0,3.66000,8.10
2,-0.09,0.384615,4.19,0.384615,-0.450,-1.03,1,0.010,0.330,0,...,0.183300,0.470,-0.390,-0.070,0.30000,0.0,14.0,0,4.33000,4.36
3,1.83,0.416667,0.40,0.250000,-0.020,-0.43,0,-0.135,0.040,0,...,0.816500,0.180,-0.020,-0.210,0.98000,0.0,14.0,0,3.40000,3.53
4,-0.04,0.222222,5.12,0.777778,-0.670,-1.04,0,0.040,0.720,0,...,0.166600,0.680,-0.630,0.010,0.74000,0.0,14.0,2,3.85000,3.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0.76,0.250000,3.91,0.375000,0.090,0.68,1,0.250,0.230,0,...,3.499900,0.360,-0.130,-0.140,14.92000,0.0,12.0,0,3.57000,3.83
24996,0.37,0.454545,8.77,0.636364,0.170,0.04,0,0.230,0.370,0,...,17.116500,0.920,0.220,0.050,25.17000,0.0,13.0,0,6.89000,7.70
24997,-0.79,0.083333,4.48,0.333333,0.360,0.27,0,0.190,0.230,0,...,3.299800,0.290,0.250,-0.030,17.00000,0.0,11.5,1,6.63000,7.48
24998,-1.09,99.000000,24.49,0.000000,-1.125,-0.42,0,0.280,0.510,0,...,107.023512,0.670,-1.345,0.525,75.53125,2.5,14.0,3,18.26375,22.26
24999,0.00,0.400000,0.01,0.333333,0.000,0.54,1,0.000,0.005,0,...,0.000000,0.175,0.000,-0.460,0.03000,0.0,14.0,0,5.42000,8.02

In [15]:
import pandas as pd
import numpy as np

# Load your CSV dataset into a pandas DataFrame
data = pd.read_csv('co.csv')

# Drop any non-numeric columns if necessary
data = data.select_dtypes(include=[np.number])

# Calculate correlation matrix
correlation_matrix = data.corr()

# Calculate inverse correlation matrix
try:
    inv_correlation_matrix = np.linalg.inv(correlation_matrix.values)
except np.linalg.LinAlgError:
    print("Error: Matrix is singular. There may be perfect multicollinearity.")
    exit()

# Calculate VIF for each column
vif_values = np.diagonal(inv_correlation_matrix)

# Create a DataFrame to store column names and VIF values
vif_data = pd.DataFrame({
    'Column': data.columns,
    'VIF': vif_values
})

# Filter columns with VIF greater than 5
high_vif_columns = vif_data[vif_data['VIF'] > 5]['Column']

# Print or use the columns with high VIF
print("Columns with VIF greater than 5:")
print(high_vif_columns)

Columns with VIF greater than 5:
Series([], Name: Column, dtype: object)